version: "3.8"

services:
  privacy-policy-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: $PORT
    container_name: privacy-policy-app
    ports:
      - "$PORT:$PORT"
    environment:
      - PORT=$PORT
    restart: unless-stopped
    command: ["npm", "run", "start"]
